//Created on 09/09/2009, 20:44:24

package view.sistema;
import Util.FabricaConexoes;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import Util.manipulaConexao;
import controler.sistema.GrupoPacoteControler;
import controler.sistema.UsuarioGrupoControler;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.sistema.GrupoData;
import model.sistema.UsuarioData;
import model.sistema.UsuarioGrupoData;
import model.sistema.UsuarioGrupo;
import model.sistema.Grupo;
import model.sistema.GrupoPacote;
import model.sistema.GrupoPacoteData;
import model.sistema.Pacote;
import model.sistema.PacoteData;
import model.sistema.Usuario;
/**
 *
 * @author Administrador
 */
public class GrupoPacoteView extends javax.swing.JInternalFrame {

    /** Creates new form UsuarioGrupoView */
    public GrupoPacoteView() {
        grupodata = new GrupoData();
        pacotedata = new PacoteData();
        grupopacotedata = new GrupoPacoteData();
        grupopacotecontroler = new GrupoPacoteControler();
        initComponents();
        jtbgrupos.getSelectionModel().addListSelectionListener(selectionListener);
        jtbgrupos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbgrupos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbpacote = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbgrupo_pacote = new javax.swing.JTable();
        jbtadicionar = new javax.swing.JButton();
        jbtremover = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Associa pacotes aos Grupos");
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setNormalBounds(new java.awt.Rectangle(0, 0, 800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setVisible(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Grupos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jtbgrupos.setModel(grupodata);
        jtbgrupos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtbgrupos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtbgrupos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pacotes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(375, 267));
        jPanel2.setRequestFocusEnabled(false);

        jtbpacote.setModel(pacotedata);
        jtbpacote.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jtbpacote.setAutoscrolls(false);
        jtbpacote.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtbpacote.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jtbpacote);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pacotes do Grupo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jtbgrupo_pacote.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtbgrupo_pacote);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtadicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add_obj.gif"))); // NOI18N
        jbtadicionar.setToolTipText("Adiciona um usuário");
        jbtadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtadicionarActionPerformed(evt);
            }
        });

        jbtremover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete_obj.gif"))); // NOI18N
        jbtremover.setToolTipText("Exclui o usuário do grupo");
        jbtremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtremoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtadicionar)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtremover)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtadicionar)
                    .addComponent(jbtremover))
                .addGap(9, 9, 9)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtremoverActionPerformed
            montaGrupoPacoteExclusao();
            grupopacotecontroler.excluir(grupopacote);
            grupopacotedata.atualizaDados();
            jtbgrupo_pacote.revalidate();
            jtbgrupo_pacote.repaint();
            atualizaTabela();
    }//GEN-LAST:event_jbtremoverActionPerformed

    private void jbtadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtadicionarActionPerformed
            montaGrupoPacote();
            grupopacotecontroler.gravar(grupopacote);
            grupopacotedata.atualizaDados();
            jtbgrupo_pacote.revalidate();
            jtbgrupo_pacote.repaint();
            atualizaTabela();

    }//GEN-LAST:event_jbtadicionarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        sql  =  "SELECT a.idpacote as Código, a.descricao as Nome from pacote a, grupo_pacote b, grupo c where a.idpacote = b.idpacote and b.idgrupo = c.idgrupo and b.idgrupo = "+grupo.getId()+"";
        manipulaConexao.preenchetable(jtbgrupo_pacote, sql);
    }//GEN-LAST:event_formComponentShown
private ListSelectionListener selectionListener = new ListSelectionListener()
    {
        public void valueChanged(ListSelectionEvent e)
        {
            atualizaTabela();
            FabricaConexoes.closeConnection();
        }
    };

 private void atualizaTabela()
 {
            int linha = jtbgrupos.getSelectedRow();
            grupo = grupodata.getGrupo(linha);
            if(!FabricaConexoes.verificaConexao()) FabricaConexoes.getConexao();
            jtbgrupo_pacote.setModel(new DefaultTableModel());
            sql  =  "SELECT a.idpacote as Código, a.descricao as Nome from pacote a, grupo_pacote b, grupo c where a.idpacote = b.idpacote and b.idgrupo = c.idgrupo and b.idgrupo = "+grupo.getId()+"";
            manipulaConexao.preenchetable(jtbgrupo_pacote, sql);
 }


private void montaGrupoPacote()
    {
        grupopacote = new GrupoPacote();
        grupo = new Grupo();
        pacote = new Pacote();
        try
        {
            int linha  = jtbgrupos.getSelectedRow();
            grupo = grupodata.getGrupo(linha);
            grupopacote.setId_grupo(grupo.getId());
            linha = jtbpacote.getSelectedRow();
            pacote = pacotedata.getPacote(linha);
            grupopacote.setId_pacote(pacote.getId());

        }
        catch(NumberFormatException e)
        {
            grupopacote.setId_pacote(0);
            grupopacote.setId_grupo(0);
        }

    }
private void montaGrupoPacoteExclusao()
{
    grupopacote = new GrupoPacote();
    try
        {
            int linha = jtbgrupos.getSelectedRow();
            grupo = grupodata.getGrupo(linha);
            linha = jtbgrupo_pacote.getSelectedRow();
            objeto = jtbgrupo_pacote.getValueAt(linha, 0);
            grupopacote.setId_pacote(Integer.valueOf(objeto.toString()));
            grupopacote.setId_grupo(grupo.getId());
            }catch(NumberFormatException e)
                    {
                        grupopacote.setId_grupo(0);
                        grupopacote.setId_pacote(0);
                        }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtadicionar;
    private javax.swing.JButton jbtremover;
    private javax.swing.JTable jtbgrupo_pacote;
    private javax.swing.JTable jtbgrupos;
    private javax.swing.JTable jtbpacote;
    // End of variables declaration//GEN-END:variables
    private GrupoData grupodata;
    private PacoteData pacotedata;
    private GrupoPacoteData grupopacotedata;
    private GrupoPacote grupopacote;
    private Grupo grupo;
    private Pacote pacote;
    private GrupoPacoteControler grupopacotecontroler;
    private Object objeto;
    private String sql;
}
