//Created on 09/09/2009, 20:44:24

package view.sistema;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import model.sistema.Pacote;
import Util.FabricaConexoes;
import Util.manipulaConexao;
import controler.sistema.ProcessoPacoteControler;
import javax.swing.table.DefaultTableModel;
import model.processo.Processo;
import model.processo.ProcessoData;
import model.sistema.PacoteData;
import model.sistema.ProcessoPacote;
import model.sistema.ProcessoPacoteData;
/**
 *
 * @author Administrador
 */
public class ProcessoPacoteView extends javax.swing.JInternalFrame {

    /** Creates new form UsuarioGrupoView */
    public ProcessoPacoteView() {
        pacotedata = new PacoteData();
        procdata = new ProcessoData();
        procpacdata = new ProcessoPacoteData();
        procpaccontroler = new ProcessoPacoteControler();
        initComponents();
        jtbpacotes.getSelectionModel().addListSelectionListener(selectionListener);
        jtbpacotes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbpacotes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbprocesso = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbproc_pac = new javax.swing.JTable();
        jbtadicionar = new javax.swing.JButton();
        jbtremover = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Associa processo aos pacotes");
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setNormalBounds(new java.awt.Rectangle(0, 0, 800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setVisible(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pacotes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jtbpacotes.setModel(pacotedata);
        jtbpacotes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtbpacotes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtbpacotes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Processos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(375, 267));
        jPanel2.setRequestFocusEnabled(false);

        jtbprocesso.setModel(procdata);
        jtbprocesso.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jtbprocesso.setAutoscrolls(false);
        jtbprocesso.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtbprocesso.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jtbprocesso);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Processos do Pacote", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jtbproc_pac.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtbproc_pac);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtadicionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/add_obj.gif"))); // NOI18N
        jbtadicionar.setToolTipText("Adiciona um usuário");
        jbtadicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtadicionarActionPerformed(evt);
            }
        });

        jbtremover.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/delete_obj.gif"))); // NOI18N
        jbtremover.setToolTipText("Exclui o usuário do grupo");
        jbtremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtremoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbtadicionar)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtremover)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtadicionar)
                    .addComponent(jbtremover))
                .addGap(9, 9, 9)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtremoverActionPerformed
            montaUsuarioGrupoExclusao();
            procpaccontroler = new ProcessoPacoteControler();
            procpaccontroler.excluir(procpac);
            procdata.atualizaDados();
            jtbproc_pac.revalidate();
            jtbproc_pac.repaint();
            selectionListener.valueChanged(null);
    }//GEN-LAST:event_jbtremoverActionPerformed

    private void jbtadicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtadicionarActionPerformed
            montaProcessoPacote();
            procpaccontroler = new ProcessoPacoteControler();
            procpaccontroler.gravar(procpac);
            procdata.atualizaDados();
            jtbproc_pac.revalidate();
            jtbproc_pac.repaint();
            selectionListener.valueChanged(null);
    }//GEN-LAST:event_jbtadicionarActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        
    }//GEN-LAST:event_formComponentShown
private ListSelectionListener selectionListener = new ListSelectionListener()
    {
        public void valueChanged(ListSelectionEvent e)
        {
                  atualizaTabela();
                  FabricaConexoes.closeConnection();
        }
    };

    private void atualizaTabela()
 {
            int linha = jtbpacotes.getSelectedRow();
            if(linha == -1) return;
            pacote = pacotedata.getPacote(linha);
            if(!FabricaConexoes.verificaConexao()) FabricaConexoes.getConexao();
            jtbproc_pac.setModel(new DefaultTableModel());
            sql  =  "SELECT a.idprocesso as Código, a.nome as Nome from processo a, pacote_processo b, pacote c where a.idprocesso = b.idprocesso and b.idpacote = c.idpacote and b.idpacote = "+pacote.getId();
            manipulaConexao.preenchetable(jtbproc_pac, sql);
            FabricaConexoes.closeConnection();
 }
private void montaProcessoPacote()
    {
        procpac = new ProcessoPacote();
        pacote = new Pacote();
        processo = new Processo();
        try
        {
            int linha  = jtbpacotes.getSelectedRow();
            pacote = pacotedata.getPacote(linha);
            procpac.setId_pacote(pacote.getId());
            linha = jtbprocesso.getSelectedRow();
            processo = procdata.getProcesso(linha);
            procpac.setId_processo(processo.getIdproceso());
        }
        catch(NumberFormatException e)
        {
            procpac.setId_processo(0);
            procpac.setId_pacote(0);
        }

    }
private void montaUsuarioGrupoExclusao()
{
    procpac = new ProcessoPacote();
    try
        {
            int linha = jtbpacotes.getSelectedRow();
            pacote = pacotedata.getPacote(linha);
            linha = jtbproc_pac.getSelectedRow();
            objeto = jtbproc_pac.getValueAt(linha, 0);
            procpac.setId_processo(Integer.valueOf(objeto.toString()));
            procpac.setId_pacote(pacote.getId());
            }catch(NumberFormatException e)
                    {
                        procpac.setId_processo(0);
                        procpac.setId_pacote(0);
                        }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtadicionar;
    private javax.swing.JButton jbtremover;
    private javax.swing.JTable jtbpacotes;
    private javax.swing.JTable jtbproc_pac;
    private javax.swing.JTable jtbprocesso;
    // End of variables declaration//GEN-END:variables
    private PacoteData pacotedata;
    private ProcessoData procdata;
    private ProcessoPacoteData procpacdata;
    private ProcessoPacote procpac;
    private Processo processo;
    private Pacote pacote;
    private ProcessoPacoteControler procpaccontroler;
    private Object objeto;
    private String sql;
}
