/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ConsultaProcesso.java
 *
 * Created on 28/10/2009, 09:02:55
 */

package view.execucao;

import Util.manipulaConexao;
import javax.swing.JOptionPane;
import model.processo.AtivProcDao;
import model.sistema.Usuario;
import view.processo.ListaLinkView;

/**
 *
 * @author Administrador
 */
public class ConsultaProcView extends javax.swing.JDialog {

    /** Creates new form ConsultaProcesso */
    public ConsultaProcView(java.awt.Frame parent, boolean modal,ListaLinkView gestao){
        super(parent, modal);
        initComponents();
        this.gestao = gestao;
        Usuario user = manipulaConexao.getUsuarioLogado();
        String sql = "Select idprocesso as 'Código', nome as 'Nome', descricao as 'Descricao' from processo" +
                " where status = 1";
        manipulaConexao.preenchetable(jTable1, sql);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbtok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Processo");
        setResizable(false);

        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        jbtok.setText("OK");
        jbtok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbtok, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtok)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-479)/2, (screenSize.height-421)/2, 479, 421);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtokActionPerformed

        try{

            int linha = jTable1.getSelectedRow();
            if(linha == -1)
            {
                JOptionPane.showMessageDialog(null, "Não há processo selecionado, verifique!");
                return;
            }
            gestao.id = gestao.model.id;
            int idprocesso =  Integer.valueOf(String.valueOf(jTable1.getValueAt(linha,0)));
            new AtivProcDao().linkProcesso(idprocesso, gestao.chave_ext, gestao.id);
            gestao.model.carregaArvore(gestao.id);
            }catch(Exception sql)
            {
                JOptionPane.showMessageDialog(null, sql.getMessage());
            }
        dispose();
    }//GEN-LAST:event_jbtokActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ConsultaProcView dialog = new ConsultaProcView(new javax.swing.JFrame(), true, new ListaLinkView(null, true, null,0));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtok;
    // End of variables declaration//GEN-END:variables
    private ListaLinkView gestao;
}
