/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DescTarefaView.java
 *
 * Created on 31/08/2010, 10:02:14
 */

package view.execucao;

/**
 *
 * @author Administrador
 */
public class DescTarefaView extends javax.swing.JInternalFrame {

    /** Creates new form DescTarefaView */
    public DescTarefaView(String valor) {
        initComponents();
        setValor(valor);
    }
    public void setValor(String valor)
    {
        jTextArea1.setText(valor);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jbt_back = new javax.swing.JButton();
        jbt_forward = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Descrição da Tarefa");

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText(" ");
        jTextArea1.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextArea1);

        jbt_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/backward_nav.gif"))); // NOI18N
        jbt_back.setEnabled(false);
        jPanel1.add(jbt_back);

        jbt_forward.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/forward_nav.gif"))); // NOI18N
        jbt_forward.setEnabled(false);
        jPanel1.add(jbt_forward);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jbt_back;
    private javax.swing.JButton jbt_forward;
    // End of variables declaration//GEN-END:variables
    private int sequencia = 0;

    public int getSequencia() {
        return sequencia;
    }

    public void setSequencia(int idtarefa) {


        this.sequencia = sequencia;
    }
    public void incrementaSequencia()
    {
        sequencia++;
    }
    public void retiraSequencia()
    {
        sequencia--;
    }
    
}
