/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ListaTipoExecucao.java
 *
 * Created on 21/10/2009, 14:14:47
 */

package view.processo;

import Util.manipulaConexao;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import model.processo.AtividadeDao;

/**
 *
 * @author Administrador
 */
public class ListaTipoExecucao extends javax.swing.JDialog {

    /** Creates new form ListaTipoExecucao */
    public ListaTipoExecucao(java.awt.Frame parent, boolean modal,ModelagemView model) {
        super(parent, modal);
        initComponents();
        this.model = model;
        index = model.jctipo.getSelectedIndex();
        if(index == 0)
        {
            
            String sql = "select * from grupo";
            manipulaConexao.preenchetable(jtbexecucao, sql);
            jtbexecucao.getSelectionModel().addListSelectionListener(selectionListener);

        }else if(index == 1)
                {
                    String sql = "select idusuario, nome, login from usuario";
                    manipulaConexao.preenchetable(jtbexecucao, sql);
                    jtbexecucao.getSelectionModel().addListSelectionListener(selectionListener);
                    }else if(index == 2)
                            {
                                return;
                                }
    }



    private ListSelectionListener selectionListener = new ListSelectionListener()
    {
        public void valueChanged(ListSelectionEvent e)
        {
            int linha = jtbexecucao.getSelectedRow();
            if(linha == -1) return;
            id = Integer.valueOf(String.valueOf(jtbexecucao.getValueAt(linha, 0)));
            nome = String.valueOf(jtbexecucao.getValueAt(linha, 1));
/*
            id =  Integer.valueOf(String.valueOf(jtbatividade.getValueAt(linha, 0)));
            try{
                ativ = new AtividadeDao().getAtividade(id);
                }catch(SQLException sql)
                {
                    JOptionPane.showMessageDialog(null,sql.getMessage(),"Erro",0);
                }*/
        }
    };


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbexecucao = new javax.swing.JTable();
        jtpesquisar = new javax.swing.JTextField();
        jbtcancel = new javax.swing.JButton();
        jbtok = new javax.swing.JButton();
        jlpesquisar = new javax.swing.JLabel();

        setTitle("");
        setResizable(false);

        jtbexecucao.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtbexecucao);

        jbtcancel.setText("Cancelar");
        jbtcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtcancelActionPerformed(evt);
            }
        });

        jbtok.setText("ok");
        jbtok.setPreferredSize(new java.awt.Dimension(75, 23));
        jbtok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtokActionPerformed(evt);
            }
        });

        jlpesquisar.setText("Pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jtpesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtcancel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jlpesquisar))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlpesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtcancel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-416)/2, (screenSize.height-321)/2, 416, 321);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtokActionPerformed
        model.setIdresp(id);
        model.jtresp.setText(nome);
        dispose();
    }//GEN-LAST:event_jbtokActionPerformed

    private void jbtcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtcancelActionPerformed
        dispose();
    }//GEN-LAST:event_jbtcancelActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListaTipoExecucao dialog = new ListaTipoExecucao(new javax.swing.JFrame(), true, new ModelagemView(new Integer(0)));
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtcancel;
    private javax.swing.JButton jbtok;
    private javax.swing.JLabel jlpesquisar;
    private javax.swing.JTable jtbexecucao;
    private javax.swing.JTextField jtpesquisar;
    // End of variables declaration//GEN-END:variables
    private ModelagemView model;
    private int index;
    private String nome;
    private int id;
}
